version: "3.1"

# docker stack deploy --compose-file docker-compose.yml placeholders

services:
  placeholders:
    image: aspnetapp

    ports:
      - 5000:5000

    environment:      
      - PLACEHOLDERSKIT_EXTENSIONS=xml,properties,config,cshtml
      - PLACEHOLDERSKIT_FOLDERS=/app
      - PLACEHOLDERSKIT_CONSUL-ADDRESS=172.17.0.1:8500
      - PLACEHOLDERSKIT_CONSUL-DATACENTER=mustach-project
      - PLACEHOLDERSKIT_CONSUL-ENDPOINT-ENVIRONMENT=/MyApplication/COMMON,/MyApplication/DEV

    command: 
      - placeholders
      
    networks:
      - placeholders-overlay
      
    deploy:
      mode: replicated
      replicas: 1
       
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
      
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

networks:
  placeholders-overlay:
    driver: overlay
   

