FROM microsoft/aspnetcore:1.1
WORKDIR /app

ADD https://github.com/fboukezzoula/PlaceholdersKit/releases/download/alpha.0.1.0/docker-dotnet-example_placeholders-alpha.0.1.0.zip /app

#ENTRYPOINT ["dotnet", "aspnetapp.dll"]
